version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    # volumes:
    #   - ./requirements/nginx/conf:/etc/nginx/conf.ddo
    #   - ./requirements/nginx/certs:/etc/nginx/certs
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
     - inception
networks:
  inception:
