version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/conf/certs:/etc/nginx/ssl

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ../data/wordpress-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_PASSWORD=${WORDPRESS_USER_PASSWORD}
    networks:
      - inception
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ../data/wordpress-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception
#alterar o path do volume para /home/fsuomins
volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/wordpress-data
      o: bind
  wordpress-db:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/wordpress-db
      o: bind

networks:
  inception:
    driver: bridge