version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_started

  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$$WP_DB_USER", "-p$$WP_DB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep php-fpm82 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/fsuomins/inception/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/fsuomins/inception/data/mariadb
      o: bind
networks:
  inception:
    driver: bridge
