FROM wordpress:latest

# Argumentos para o banco de dados
ARG WP_DATABASE_NAME
ARG WP_DATABASE_USER
ARG WP_DATABASE_PASSWORD
ARG WP_DATABASE_HOST
ARG WP_DATABASE_ROOT
ARG WP_DATABASE_ROOT_PASSWORD
ARG WP_URL
ARG WP_TITLE
ARG WP_ADMIN_USER
ARG WP_ADMIN_PASSWORD
ARG WP_ADMIN_EMAIL
ARG WP_USER
ARG WP_USER_PASSWORD
ARG WP_USER_EMAIL
ARG REDIS_HOST
ARG REDIS_PORT

# Instalar dependências (wp-cli e redis)
RUN apt-get update && apt-get install -y --no-install-recommends \
    wp-cli \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

# Copiar o script de entrada
COPY ./wp-entrypoint.sh /usr/local/bin/wp-entrypoint.sh

# Tornar o script executável
RUN chmod +x /usr/local/bin/wp-entrypoint.sh

# Copiar o wp-config.php se necessário
COPY ./conf/wp-config.php /var/www/html/wp-config.php

# Ajuste de permissões
RUN chown -R www-data:www-data /var/www/html

# Expor a porta do servidor web
EXPOSE 80

# Definir o entrypoint para o script personalizado
ENTRYPOINT ["wp-entrypoint.sh"]

# Executar o PHP-FPM
CMD ["php-fpm81", "-F"]